namespace EQClassic.Shared.Protocol;

/// <summary>
/// First byte of every application message. Values are part of the wire contract: never renumber,
/// only append (the version handshake in <see cref="ProtocolInfo"/> rejects mismatched peers).
/// </summary>
public enum MessageType : byte
{
    LoginRequest = 1,
    LoginResponse = 2,
    ServerListRequest = 3,
    ServerListResponse = 4,
    PlayRequest = 5,
    PlayResponse = 6,
    ServerHello = 7,
    SecureLoginRequest = 8,
    Sealed = 9,
    WorldLoginRequest = 10,
    WorldLoginResponse = 11,
    EnterWorldRequest = 12,
    EnterWorldResponse = 13,
    CreateCharacterRequest = 14,
    CreateCharacterResponse = 15,
    ZoneEnterRequest = 16,
    ZoneEnterResponse = 17,
    PlayerMove = 18,
    EntityPositions = 19,
    MoveCorrection = 20,
    EntitySpawned = 21,
    EntityRemoved = 22,
    ZoneChange = 23,
    ZoneDoors = 24,
    ClickDoor = 25,
    DoorState = 26,
    ZoneMessage = 27,
    SetTarget = 28,
    AutoAttack = 29,
    CombatEvent = 30,
    PlayerHealth = 31,
    ConsiderRequest = 32,
    ConsiderResult = 33,
    SetSitting = 34,
    EntityAppearance = 35,
    ChatSend = 36,
    ChatMessage = 37,
    WhoRequest = 38,
    PlayerExperience = 39,
    ZoneInfo = 40,
    TimeOfDay = 41,
    CreationOptionsRequest = 42,
    CreationOptionsResponse = 43,
    LootRequest = 44,
    LootTake = 45,
    LootEnd = 46,
    LootContents = 47,
    PlayerInventory = 48,
    MoveItem = 49,
    SpellBook = 50,
    MemorizeSpell = 51,
    CastSpell = 52,
    SpellCast = 53,
    PlayerMana = 54,
    ScribeScroll = 55,
    PlayerBuffs = 56,
    MerchantRequest = 57,
    MerchantGoods = 58,
    MerchantBuy = 59,
    MerchantSell = 60,
    MerchantEnd = 61,
    UseAbility = 62,
    PlayerSkills = 63,
    GroupCommand = 64,
    GroupUpdate = 65,
    ZoneWeather = 66,
    TradeCommand = 67,
    TradeWindow = 68,
    PetCommand = 69,
    BankCommand = 70,
    BankContents = 71,
}
