#!/bin/bash
# Regenerates sql/patches/004_npc_combat_stats.sql from a Quarm database dump.
#
# Needs: the eqclassic DB (dump imported, WITHOUT patch 004 applied, so our original AC is read),
#        a Quarm dump imported as DB quarm_ref
#          (SecretsOTheP/EQMacEmu utils/sql/database_full/quarm_*.tar.gz, the quarm_*.sql file),
#        mariadb client access as root (sudo mariadb) or set MYSQL="mariadb -u ... -p...".
set -euo pipefail
MYSQL=${MYSQL:-sudo mariadb --skip-ssl}
OUT=${1:-sql/patches/004_npc_combat_stats.sql}
TSV=$(mktemp)

# 1. Match NPCs: name + zone (id / 1000) + level within Quarm's level range +-2 (ids are not stable).
$MYSQL -e "
CREATE DATABASE IF NOT EXISTS work;
DROP TABLE IF EXISTS work.npc_match;
CREATE TABLE work.npc_match AS
SELECT o.id our_id, MIN(q.id) quarm_id, COUNT(*) candidates
FROM eqclassic.npc_types o
JOIN quarm_ref.npc_types q ON q.name = o.name AND FLOOR(q.id / 1000) = FLOOR(o.id / 1000)
 AND CAST(o.level AS SIGNED) BETWEEN CAST(q.level AS SIGNED) - 2 AND CAST(GREATEST(q.level, q.maxlevel) AS SIGNED) + 2
GROUP BY o.id;"

# 2. Absolute stats per NPC: Quarm values when matched, otherwise ours with AC rescaled by the
#    per-level-band ratio measured on the matched pairs (AVG(our AC / Quarm AC)).
$MYSQL -N -B -e "
SELECT o.id,
  IF(q.id IS NULL, o.hp, q.hp), IF(q.id IS NULL, o.mindmg, q.mindmg), IF(q.id IS NULL, o.maxdmg, q.maxdmg),
  IF(q.id IS NULL, ROUND(o.AC / CASE WHEN o.level<10 THEN 3.89 WHEN o.level<20 THEN 3.68 WHEN o.level<30 THEN 4.83
     WHEN o.level<40 THEN 5.91 WHEN o.level<50 THEN 7.05 WHEN o.level<60 THEN 8.15 WHEN o.level<70 THEN 7.51 ELSE 10.74 END), q.AC),
  IFNULL(q.ATK,0), IFNULL(q.Accuracy,0), IFNULL(q.avoidance,0), IF(q.id IS NULL,0,1)
FROM eqclassic.npc_types o LEFT JOIN work.npc_match m ON m.our_id = o.id
LEFT JOIN quarm_ref.npc_types q ON q.id = m.quarm_id ORDER BY o.id;" > "$TSV"

# 3. Write the patch (header, ALTERs, temp table, batched INSERTs, UPDATEs).
python3 - "$TSV" "$OUT" <<'PY'
import sys
rows = [l.rstrip('\n').split('\t') for l in open(sys.argv[1])]
matched = sum(1 for r in rows if r[8] == '1')
out = [f"""-- NPC combat stats for the EQMacEmu-derived melee model (Zone/Include/CombatFormulas.h).
--
-- The formulas and the stats go together: the old DB used its own AC scale (4-8x higher) and
-- lower HP. Values come from the Quarm database (SecretsOTheP/EQMacEmu, utils/sql/database_full),
-- matched on name + zone (id / 1000) + level within Quarm's level range +-2,
-- because NPC ids are not stable between the two databases.
--   {matched} NPCs take Quarm's hp, mindmg, maxdmg, AC, ATK, Accuracy, avoidance;
--   {len(rows) - matched} unmatched NPCs keep their values, AC rescaled by the measured per-level-band
--   ratio (3.89 at 1-9 ... 8.15 at 50-59) so every NPC is on the same scale.
-- Absolute values: running this patch twice is harmless.
-- Generated by tools/npc_stats/gen_004.sh; regenerate rather than edit by hand.

ALTER TABLE npc_types
  ADD COLUMN IF NOT EXISTS ATK int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS Accuracy int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avoidance int(11) NOT NULL DEFAULT 0;
ALTER TABLE npc_types_without
  ADD COLUMN IF NOT EXISTS ATK int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS Accuracy int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avoidance int(11) NOT NULL DEFAULT 0;

DROP TEMPORARY TABLE IF EXISTS npc_combat_stats;
CREATE TEMPORARY TABLE npc_combat_stats (
  id int(11) NOT NULL PRIMARY KEY, hp int(11) NOT NULL, mindmg int(11) NOT NULL, maxdmg int(11) NOT NULL,
  AC int(11) NOT NULL, ATK int(11) NOT NULL, Accuracy int(11) NOT NULL, avoidance int(11) NOT NULL
);
"""]
for i in range(0, len(rows), 1000):
    out.append("INSERT INTO npc_combat_stats VALUES\n" + ",\n".join("(" + ",".join(r[:8]) + ")" for r in rows[i:i+1000]) + ";\n")
out.append("""
UPDATE npc_types o JOIN npc_combat_stats s ON s.id = o.id
  SET o.hp = s.hp, o.mindmg = s.mindmg, o.maxdmg = s.maxdmg, o.AC = s.AC,
      o.ATK = s.ATK, o.Accuracy = s.Accuracy, o.avoidance = s.avoidance;
UPDATE npc_types_without o JOIN npc_combat_stats s ON s.id = o.id
  SET o.hp = s.hp, o.mindmg = s.mindmg, o.maxdmg = s.maxdmg, o.AC = s.AC,
      o.ATK = s.ATK, o.Accuracy = s.Accuracy, o.avoidance = s.avoidance;
DROP TEMPORARY TABLE npc_combat_stats;
""")
open(sys.argv[2], 'w').write("".join(out))
print(f"{len(rows)} NPCs, {matched} matched -> {sys.argv[2]}")
PY
rm -f "$TSV"
