#!/bin/bash
# Regenerates sql/patches/011_npc_sizes.sql: NPC sizes from the Quarm database (quarm_ref, see
# gen_004.sh), for the NPCs matched the same way (name + zone + level within Quarm's range +-2).
# Ours were often wrong: wolves at half size, Skyshrine dragons at 1 instead of 6, -1 on many.
# Needs read access to eqclassic and quarm_ref (MYSQL, default: the eqc user).
set -euo pipefail
MYSQL=${MYSQL:-mysql --skip-ssl -ueqc -peqc}
OUT=${1:-sql/patches/011_npc_sizes.sql}
ROWS=$($MYSQL -N -B -e "
CREATE TEMPORARY TABLE eqclassic.tmp_size_match AS
SELECT o.id our_id, MIN(q.id) quarm_id FROM eqclassic.npc_types o
JOIN quarm_ref.npc_types q ON q.name = o.name AND FLOOR(q.id / 1000) = FLOOR(o.id / 1000)
 AND CAST(o.level AS SIGNED) BETWEEN CAST(q.level AS SIGNED) - 2 AND CAST(GREATEST(q.level, q.maxlevel) AS SIGNED) + 2
GROUP BY o.id;
SELECT o.id, o.size, q.size, o.name
FROM eqclassic.npc_types o JOIN eqclassic.tmp_size_match m ON m.our_id = o.id JOIN quarm_ref.npc_types q ON q.id = m.quarm_id
WHERE o.size <> q.size AND q.size > 0
ORDER BY o.id;")
python3 - "$OUT" <<PY
import sys
rows = [l.split('\t') for l in """$ROWS""".splitlines() if l.strip()]
out = ["""-- NPC sizes from the Quarm database (SecretsOTheP/EQMacEmu, utils/sql/database_full), for the NPCs
-- matched on name + zone (id / 1000) + level within Quarm's range +-2 (as patch 004).
-- Ours were often wrong: wolves at about half size (a_young_dire_wolf 2 instead of 4), Skyshrine
-- dragons at 1 instead of 6, -1 on many Luclin-era NPCs. %d NPCs change; the others keep theirs.
-- The previous sizes are kept in npc_types_size_before_011. Absolute values: running it twice is harmless.
-- Generated by tools/npc_stats/gen_011_sizes.sh; regenerate rather than edit by hand.

CREATE TABLE IF NOT EXISTS npc_types_size_before_011 AS SELECT id, size FROM npc_types;
""" % len(rows)]
for i in range(0, len(rows), 200):
    chunk = rows[i:i + 200]
    out.append('UPDATE npc_types SET size = CASE id\n' + '\n'.join('  WHEN %s THEN %s' % (r[0], r[2]) for r in chunk)
               + '\n  ELSE size END\nWHERE id IN (%s);' % ','.join(r[0] for r in chunk))
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
print(len(rows), 'NPCs')
PY
