#!/bin/bash
# Regenerates sql/patches/019_post_velious_additions.sql: the spawn entries of NPCs added to era zones
# after Velious. An NPC is taken when
#   - its name ('#', case, trailing '_' ignored) is in no zone of the Quarm database (quarm_ref) and not
#     in the 2000-2002 ShowEQ capture (EQSpawns-showeq-2002.txt, also without a/an/the), and
#   - no point of its spawn group is within 15 units of a Quarm spawn point of the zone: an era NPC
#     under another name (Kael's randomly named giants, Di`zok / Dizok) sits on an era point, an
#     addition stands where nothing stood, and
#   - it is not an invisible controller (race 127: they may drive scripted events), and
#   - it does not carry a title Quarm has in the same zone ("Adjutant_...", "Senior_Guard_...": Kael's
#     giants have random names, so theirs never match).
# Zones Quarm does not have (hateplaneb, tutorialb, gukta) are left alone; zones in a wholly later
# state are handled by gen_zone_from_quarm.py. Usage: gen_019_post_velious.sh [output]
set -e
cd "$(dirname "$0")/../.."
OUT=${1:-sql/patches/019_post_velious_additions.sql}
M="mysql --skip-ssl -u${EQC_DB_USER:-eqc} -p${EQC_DB_PASS:-eqc} --local-infile=1 ${EQC_DB_NAME:-eqclassic}"
TMP=$(mktemp)
awk -F'\t' 'NR>1{n=tolower($1); gsub(/ /,"_",n); sub(/^(an|a|the)_/,"",n); print n}' tools/npc_stats/EQSpawns-showeq-2002.txt | sort -u > "$TMP"
$M -N -e "
CREATE TEMPORARY TABLE qn (name VARCHAR(64) PRIMARY KEY);
INSERT IGNORE INTO qn SELECT TRIM(BOTH '_' FROM LOWER(REPLACE(name,'#',''))) FROM quarm_ref.npc_types;
CREATE TEMPORARY TABLE sq (name VARCHAR(64) PRIMARY KEY);
LOAD DATA LOCAL INFILE '$TMP' IGNORE INTO TABLE sq;
CREATE TEMPORARY TABLE qt (zid INT, title VARCHAR(64), PRIMARY KEY (zid, title));
INSERT IGNORE INTO qt SELECT FLOOR(id/1000), SUBSTRING_INDEX(LOWER(REPLACE(name,'#','')), '_', 1) FROM quarm_ref.npc_types WHERE name LIKE '%\\_%';
CREATE TEMPORARY TABLE cand (id INT PRIMARY KEY) AS SELECT DISTINCT n.id FROM spawnentry e JOIN npc_types n ON n.id = e.npcID
  LEFT JOIN qn ON qn.name = TRIM(BOTH '_' FROM LOWER(REPLACE(n.name,'#','')))
  LEFT JOIN sq ON sq.name = REGEXP_REPLACE(TRIM(BOTH '_' FROM LOWER(REPLACE(n.name,'#',''))),'^(an|a|the)_','')
  WHERE qn.name IS NULL AND sq.name IS NULL AND n.race <> 127
    AND NOT (REPLACE(n.name,'#','') REGEXP BINARY '^[A-Z]' AND EXISTS (SELECT 1 FROM qt WHERE qt.zid = FLOOR(n.id/1000)
             AND qt.title = SUBSTRING_INDEX(LOWER(REPLACE(n.name,'#','')), '_', 1)));
CREATE TEMPORARY TABLE qp (zone VARCHAR(32), x FLOAT, y FLOAT, gx INT, gy INT, KEY (zone, gx, gy));
INSERT INTO qp SELECT zone, x, y, ROUND(x/30), ROUND(y/30) FROM quarm_ref.spawn2;
CREATE TEMPORARY TABLE gnear AS SELECT s.spawngroupID g, MIN(s.zone) zone, COUNT(DISTINCT s.zone) zones,
  MAX(EXISTS(SELECT 1 FROM qp WHERE qp.zone = s.zone AND qp.gx BETWEEN ROUND(s.x/30)-1 AND ROUND(s.x/30)+1
             AND qp.gy BETWEEN ROUND(s.y/30)-1 AND ROUND(s.y/30)+1 AND ABS(qp.x-s.x) < 15 AND ABS(qp.y-s.y) < 15)) near
  FROM spawn2 s WHERE s.spawngroupID IN (SELECT spawngroupID FROM spawnentry WHERE npcID IN (SELECT id FROM cand)) GROUP BY s.spawngroupID;
SELECT g.zone, e.spawngroupID, e.npcID, n.name, n.level FROM spawnentry e JOIN gnear g ON g.g = e.spawngroupID JOIN npc_types n ON n.id = e.npcID
  WHERE e.npcID IN (SELECT id FROM cand) AND g.near = 0 AND g.zones = 1
    AND g.zone IN (SELECT short_name FROM quarm_ref.zone) AND g.zone IN (SELECT DISTINCT zone FROM quarm_ref.spawn2)
  ORDER BY g.zone, e.npcID, e.spawngroupID" 2>/dev/null > "$TMP.rows"
N=$(wc -l < "$TMP.rows"); Z=$(cut -f1 "$TMP.rows" | sort -u | wc -l)
{
echo "-- 019: spawn entries of NPCs added to era zones after Velious ($N entries in $Z zones)."
echo "--"
echo "-- The undead army of the Feerrott and Toxxulia, Luclin's translocators and exterminators in the cities,"
echo "-- Siren's Grotto's level 55+ sirens, and the like: NPCs that are in neither the Quarm database nor the"
echo "-- 2000-2002 ShowEQ capture, and whose spawn group has no point within 15 units of a Quarm spawn point"
echo "-- (an era NPC under another name sits on an era point; these stand where nothing stood). Invisible"
echo "-- controllers (race 127) are kept. Generated by tools/npc_stats/gen_019_post_velious.sh."
echo "-- The rows move to spawnentry_post_velious, as in 012 (restore: INSERT INTO spawnentry SELECT ...). Idempotent."
echo "--"
cut -f1,4 "$TMP.rows" | sed 's/[0-9]*$//' | sort | uniq -c | awk '{printf "-- %s: %s x%s\n", $2, $3, $1}'
echo
echo "CREATE TABLE IF NOT EXISTS spawnentry_post_velious LIKE spawnentry;"
echo "CREATE TEMPORARY TABLE era_019 (spawngroupID INT, npcID INT, PRIMARY KEY (spawngroupID, npcID));"
echo "INSERT INTO era_019 VALUES"
awk -F'\t' '{printf "%s(%s, %s)", (NR>1 ? ",\n" : ""), $2, $3} END {print ";"}' "$TMP.rows"
echo "INSERT IGNORE INTO spawnentry_post_velious SELECT e.* FROM spawnentry e JOIN era_019 x ON x.spawngroupID = e.spawngroupID AND x.npcID = e.npcID;"
echo "DELETE e FROM spawnentry e JOIN era_019 x ON x.spawngroupID = e.spawngroupID AND x.npcID = e.npcID;"
echo "DROP TEMPORARY TABLE era_019;"
} > "$OUT"
rm -f "$TMP" "$TMP.rows"
echo "$OUT: $N entries in $Z zones"
