-- 019: spawn entries of NPCs added to era zones after Velious (414 entries in 76 zones).
--
-- The undead army of the Feerrott and Toxxulia, Luclin's translocators and exterminators in the cities,
-- Siren's Grotto's level 55+ sirens, and the like: NPCs that are in neither the Quarm database nor the
-- 2000-2002 ShowEQ capture, and whose spawn group has no point within 15 units of a Quarm spawn point
-- (an era NPC under another name sits on an era point; these stand where nothing stood). Invisible
-- controllers (race 127) are kept. Generated by tools/npc_stats/gen_019_post_velious.sh.
-- The rows move to spawnentry_post_velious, as in 012 (restore: INSERT INTO spawnentry SELECT ...). Idempotent.
--
-- akanon: a_defective_cleaner x1
-- akanon: Exterminator_VIII x2
-- akanon: Gilipus x1
-- akanon: Golsodix_Biroboddle x1
-- akanon: Tamno_Shifa x1
-- befallen: Zeek x1
-- burningwood: a_loyal_follower x1
-- burningwood: Asmodin_Jru`dac x1
-- butcher: a_Tunarian_scout x1
-- butcher: Dandalek_Swillslammer x1
-- butcher: Lieutenant_Gattek x1
-- butcher: Renell_Bekea x1
-- butcher: Rokaon_Sternheart x1
-- cabeast: Exterminator_Sahizz x1
-- cabeast: Pagnar_Vyng x1
-- cauldron: Grimpl_Rustedcog x3
-- cauldron: Henai_Silentwalker x1
-- cauldron: Praklion_of_the_Cauldron x1
-- cauldron: Treanik_Ireblade x1
-- charasis: a_pulsating_bile x4
-- chardok: #Tani_Cogswin x1
-- citymist: a_corrupt_spiritualist x3
-- citymist: #Dread_Wraith x2
-- citymist: #Ravenous_War_Bone_Skeleton x1
-- commons: Bealya_Tanilsuia x1
-- dreadlands: a_loyal_follower x1
-- dreadlands: Remnant_Spirit x1
-- dreadlands: #Time_Torn_Acolyte x1
-- eastkarana: #Izera_N`Kar x1
-- eastwastes: a_rygorr_centurion x1
-- eastwastes: a_RyGorr_snow_trooper x1
-- ecommons: Almon_Juliao x1
-- ecommons: Badoo_Zumlar x1
-- ecommons: Barstre_Songweaver x1
-- ecommons: Cedric_Bramblethorn x1
-- ecommons: Chaenz_Abella x1
-- ecommons: Elin_Lightblade x1
-- ecommons: Kehn_Kohski x1
-- ecommons: Khaite_Ranna x1
-- ecommons: Luarnn_Gibbizt x1
-- ecommons: Magus_Zeir x1
-- ecommons: Olin_Helni x1
-- ecommons: Palik_Agrolm x1
-- ecommons: Tallik_Jaggedfire x1
-- ecommons: Uyennli_V`Drimw x1
-- ecommons: Uzmanya_Zsiksta x1
-- ecommons: Voris_Flatblade x1
-- ecommons: Wilno_Lilin x1
-- ecommons: Xernic_Gutner x1
-- emeraldjungle: an_iksar_traitor x1
-- emeraldjungle: a_reflective_soul x1
-- emeraldjungle: Disease-Ridden_Gorilla x1
-- emeraldjungle: Lativ x1
-- emeraldjungle: totem_fiendling x1
-- erudnext: Bazma_Brinstar x1
-- erudnext: Brianna_Falsruinay x1
-- erudnext: Ienala_Eceiaiu x1
-- erudnext: #Jordin_Sretin x1
-- erudnext: Kordian_Keshalian x1
-- erudnext: #Senina_Jolik x1
-- erudnext: Silos_Dumont x1
-- erudnext: #Translocator_Eniela x1
-- erudnext: Valani_Gadriek x1
-- erudnint: Barodreth_Firefingers x1
-- erudsxing: a_zombie_guardian x1
-- erudsxing: #Translocator_Jempar x1
-- erudsxing: undead_erudite_sailor x1
-- erudsxing: undead_troll_sailor x1
-- erudsxing: Yun_Assistant_Maldok x1
-- everfrost: a_gigantic_wooly_spider x13
-- everfrost: Gizula x1
-- everfrost: Kipler_Steffeal x1
-- everfrost: Kizpi_Taelwx x1
-- everfrost: Magus_Delin x1
-- everfrost: Mannis_McGuyett x1
-- everfrost: Qileour_Bahiael x1
-- everfrost: Trelsa_McKindle x1
-- everfrost: Yalienn_Laeianse x1
-- everfrost: Zweznyi_Xeiw x1
-- fearplane: Essence_of_Rage x1
-- fearplane: Ireblind_Imp x1
-- feerrott: a_skeletal_commander x5
-- feerrott: a_skeletal_conscript x8
-- feerrott: a_skeletal_footsoldier x13
-- feerrott: a_skeletal_lieutenant x2
-- feerrott: a_skeletal_trooper x16
-- feerrott: #Emissary_Shinsere x1
-- feerrott: Grinak x1
-- felwithea: Ann_Oma x1
-- felwithea: Exterminator_Valern x1
-- felwithea: Larroniae_Huial x1
-- fieldofbone: a_large_heartsting_scorpion x2
-- fieldofbone: Burynai-bane_Spider x1
-- fieldofbone: Burynai_Cutter x1
-- fieldofbone: Hierophant_Liyx x1
-- fieldofbone: Mardic_Crimsonsteel x1
-- fieldofbone: Vesh_Tailwhip x1
-- firiona: Assistant_Buford x1
-- firiona: Gillia_Brissok x1
-- firiona: Rinnala_Sweetsong x1
-- firiona: Wekland_Greenfoot x1
-- freporte: a_grubby_rogue x1
-- freporte: Cartographer_Piri x1
-- freporte: Exterminator_Larkey x1
-- freporte: Gartrog_Smitehammer x1
-- freporte: Jasmine_Yiur x1
-- freporte: Miocaei_Herlsas x1
-- freporte: Ralfson_Gerositan x1
-- freporte: #Translocator_Setikan x1
-- freportn: Gayle_Seesill x1
-- freportn: Karl_Saffio x1
-- freportw: Exterminator_Qalantir x1
-- freportw: Ginehl_Wiquar x1
-- freportw: Phineas_Taylor x1
-- freportw: Taxonomist_Darwin_Grisk x1
-- freportw: Trithalis_Leredar x1
-- frontiermtns: #Cenobite_Pakclaw x1
-- frontiermtns: #Digmaster_Duggert x1
-- frontiermtns: #Rock_Shaper_Dritam x1
-- gfaydark: Enyaanuia_Windancer x1
-- gfaydark: Faerik_Windrunner x1
-- gfaydark: Hegwal_Miffs x1
-- gfaydark: Katryn_Hidken x1
-- gfaydark: Niflel_Faliwae x1
-- growthplane: an_entoling_essence_conduit x1
-- gukbottom: #a_corrupted_gnome_explorer x1
-- gukbottom: Zol_Ghoul_Knight x1
-- halas: Balgros_McMichael x1
-- halas: Boster_MacHadden x1
-- halas: Conladan_Kevellian x1
-- halas: Elgar_Donbrand x1
-- halas: Grots x1
-- halas: Haladorf_Wuirgon x1
-- halas: Rollian_Galothar x1
-- halas: Wrait_Chimera x1
-- highpass: Shumpi_Wimahnn x1
-- iceclad: #Translocator_Kurione x1
-- jaggedpine: Ervonis_Leaflow x2
-- kaesora: a_corrupt_spiritualist x1
-- kaladima: Grasill_Stoutale x1
-- kaladimb: a_rodent x2
-- kaladimb: Exterminator_Vin x1
-- kaladimb: Goriba_Thurgorson x1
-- kaladimb: Tabber_Varhund x1
-- kithicor: Dusis_Moor x1
-- kithicor: Tarnamil x1
-- kurn: #a_burynai_flesh_reaper x1
-- lakeofillomen: Crix_Tzo`mok x1
-- lakeofillomen: Doovix_Mruzzik x1
-- lakeofillomen: Keras_McArik x1
-- lakeofillomen: Lingering_Axefall x1
-- lakeofillomen: Pagik_Tsissun x1
-- lakeofillomen: Syrik_Iceblood x1
-- lakeofillomen: Xiokai_Rissthrum x1
-- lakeofillomen: Yimic_Pxo`hab x1
-- lakerathe: #Guja_Master_Therik x1
-- lfaydark: Elwinn_Prelliaen x1
-- mistmoore: Eirod_Haerod x1
-- mistmoore: #Sir_Bronthas x1
-- misty: a_halfling_zombie x4
-- misty: epicurean_halfling x1
-- misty: Roha_Jumthief x1
-- necropolis: a_bloodthirsty_carrion_bat x1
-- necropolis: a_deadly_phase_spider x1
-- necropolis: a_great_green_slime x1
-- necropolis: #an_Odd_Looking_Spider x2
-- nektulos: a_leatherfoot_skeleton x1
-- nektulos: a_rotting_initiate x1
-- nektulos: Blugurg x1
-- nektulos: #First_Fragment_of_Igok x1
-- nektulos: Glob x1
-- nektulos: Kinliat_Bloodwalker x1
-- nektulos: Vol_T`Vke x1
-- neriaka: a_Teir`Dal_correspondent x1
-- neriaka: Exterminator_Filrog x1
-- neriaka: Goldush x1
-- neriaka: Grallvek x1
-- neriaka: Grigdor x1
-- neriaka: Javen_TaVos x1
-- neriaka: Luruk_Dridor x1
-- neriaka: Martok x1
-- neriaka: Nalissi_K`Ten x1
-- neriaka: Nerta_D`Vile x1
-- neriaka: Prashnak x1
-- neriaka: Scartok x1
-- neriaka: Zignal_Luk x1
-- neriakb: Exterminator_Damasi x1
-- neriakb: Fleshweaver_T`soma x1
-- neriakc: Exterminator_Gilea x1
-- neriakc: #Gribnor`s_Thug x1
-- neriakc: #Gribnor`s_Thug_ x1
-- neriakc: #Gribnor_the_Small x1
-- nro: a_gila_monster x2
-- nro: Odwren_Werat x1
-- nro: #Verrell_Cogswin x1
-- oasis: #Arthikus x1
-- oggok: Baddi_Waca x1
-- oggok: Bakrishal x1
-- oggok: Exterminator_Glurg x3
-- oggok: Goobast x1
-- oggok: Gralbug x1
-- oggok: Gronk x1
-- oggok: Kulver x1
-- oggok: Mooglan x1
-- oggok: Murak x1
-- oggok: Ogomok x1
-- oggok: Puwdap x1
-- oggok: Sheerie_Oglarum x1
-- oot: Gubblegrot_Smashfist x1
-- oot: Raotin_Teawel x1
-- overthere: a_sarnak_messenger x1
-- overthere: #High_Priest_I`Xar x1
-- overthere: Osvima_K`Matim x1
-- overthere: Pungub_Brawlum x1
-- overthere: #Translocator_Breya x1
-- overthere: Vaxxim_T`Quoren x1
-- overthere: #Yiln_Darksly x1
-- paineel: Erandi_Natasu x1
-- paineel: Shyna_Cintya x1
-- paineel: Toryn_Roltaire x1
-- paineel: Yenlr_Undraie x1
-- qcat: Vach_Piral x1
-- qeynos2: Exterminator_Wintloag x1
-- qeynos2: Gabrielle_Spirit x1
-- qeynos: Christian_Hidken x1
-- qeynos: Exterminator_Rasmon x1
-- qeynos: #Translocator_Sedina x1
-- qeynos: Warehnn_Awlne x1
-- qeytoqrg: a_skeletal_trooper x1
-- qeytoqrg: Sarri_Modav x1
-- qeytoqrg: Ubzial_Iyeaql x1
-- qrg: Mikkai_Nomak x1
-- qrg: Qaelin_Hailstorm x1
-- rathemtn: a_minion_of_Ytyrs x1
-- rathemtn: #a_pile_of_froglok_remains x1
-- rathemtn: Nemeen_Pekasr x1
-- rivervale: Exterminator_Sutten x1
-- rivervale: Fento_Jalla x1
-- rivervale: Jimbledorp_Heptybak x1
-- sirens: a_coldspine_seahorse x1
-- sirens: a_neriad_weaver x1
-- sirens: a_siren_beguiler x7
-- sirens: #a_siren_coercer x1
-- sirens: a_siren_myrmidon x10
-- sirens: a_siren_templar x9
-- sirens: a_walrus_servant x6
-- southkarana: a_wolf_cub x1
-- sro: Farwein_Windrun x1
-- steamfont: a_mechanical_merchant x1
-- steamfont: a_mountain_lion x2
-- steamfont: Bigilam_Wantilans x1
-- steamfont: Metallurgist_Mirakzin x1
-- stonebrunt: a_Kejekan_ghazi x1
-- stonebrunt: a_scorned_shiphand x1
-- stonebrunt: Gnashing_Kobold x1
-- stonebrunt: Walker_Stormfyre x1
-- swampofnohope: Assassin_Radal x1
-- swampofnohope: Axle x1
-- swampofnohope: High_Priest_Teloras x1
-- swampofnohope: Oracle_Estra x1
-- thurgadina: Glatigi x1
-- timorous: a_streamer x7
-- tox: a_skeletal_commander x3
-- tox: a_skeletal_conscript x2
-- tox: a_skeletal_footsoldier x10
-- tox: a_skeletal_lieutenant x2
-- tox: a_skeletal_trooper x11
-- tox: Assistant_T`os x1
-- tox: Dovon_Traical x1
-- tox: Fittorin_Bladespur x1
-- tox: Ilisiv_Gantrau x1
-- tox: Reeking_Skunk x1
-- trakanon: a_Krup_Wanderer x1
-- trakanon: an_Undead_Sebilisian_Lich x2
-- trakanon: a_Sebilisian_Battlemaster x3
-- trakanon: a_Sebilisian_Revenant x2
-- trakanon: Lativ x1
-- veeshan: a_furious_guardian_wurm x1
-- veeshan: an_ancient_racnar x1
-- veeshan: a_savage_racnar x1
-- warslikswood: Lurking_Hopeful x1
-- westwastes: a_drake_outcast x1

CREATE TABLE IF NOT EXISTS spawnentry_post_velious LIKE spawnentry;
CREATE TEMPORARY TABLE era_019 (spawngroupID INT, npcID INT, PRIMARY KEY (spawngroupID, npcID));
INSERT INTO era_019 VALUES
(55001, 55005),
(55043, 55016),
(55060, 55019),
(55195, 55153),
(55201, 55159),
(55043, 55175),
(36127, 36055),
(87139, 87081),
(87242, 87145),
(68278, 68112),
(68291, 68122),
(68292, 68123),
(68301, 68132),
(189301, 68247),
(106028, 106009),
(106162, 106118),
(70000, 70000),
(70038, 70022),
(70061, 70032),
(70062, 70033),
(70038, 70050),
(70038, 70052),
(105030, 105022),
(105054, 105043),
(105215, 105137),
(105035, 105147),
(103102, 103040),
(90121, 90087),
(90081, 90102),
(90051, 90120),
(90154, 90120),
(90121, 90166),
(90121, 90169),
(21120, 21070),
(86148, 86089),
(86210, 86099),
(86148, 86150),
(189711, 15158),
(116059, 116045),
(116645, 116523),
(22143, 22082),
(22144, 22083),
(22145, 22084),
(22146, 22085),
(22147, 22086),
(22148, 22087),
(22149, 22088),
(22165, 22104),
(22167, 22106),
(22169, 22108),
(22170, 22109),
(22171, 22110),
(22172, 22111),
(22173, 22112),
(22175, 22114),
(22176, 22115),
(22177, 22116),
(22179, 22118),
(94051, 94037),
(94157, 94072),
(94265, 94120),
(94112, 94130),
(94021, 94139),
(24030, 24031),
(24031, 24032),
(24032, 24033),
(24088, 24095),
(24089, 24096),
(24091, 24098),
(24093, 24100),
(24094, 24101),
(189728, 24113),
(23067, 23076),
(98016, 98008),
(98047, 98023),
(98049, 98024),
(98090, 98043),
(98093, 98045),
(30041, 30042),
(30075, 30042),
(30078, 30042),
(30041, 30043),
(30042, 30043),
(30077, 30043),
(30078, 30043),
(30042, 30055),
(30075, 30055),
(30077, 30055),
(30076, 30056),
(30041, 30057),
(30077, 30057),
(30160, 30079),
(30161, 30080),
(30162, 30081),
(30163, 30082),
(30164, 30083),
(30165, 30084),
(30166, 30085),
(30168, 30087),
(30169, 30088),
(72129, 72068),
(72133, 72069),
(47003, 47003),
(47004, 47004),
(47005, 47005),
(47006, 47006),
(47007, 47007),
(47008, 47008),
(47009, 47009),
(47010, 47010),
(47011, 47011),
(47012, 47012),
(47013, 47013),
(47014, 47014),
(47015, 47015),
(47016, 47016),
(47028, 47018),
(47021, 47019),
(47022, 47020),
(47023, 47021),
(47024, 47022),
(47025, 47023),
(47029, 47024),
(47030, 47025),
(47031, 47026),
(47032, 47027),
(47033, 47028),
(47049, 47029),
(47035, 47030),
(47036, 47031),
(47037, 47032),
(47038, 47033),
(47040, 47034),
(47046, 47035),
(47047, 47036),
(47053, 47039),
(47054, 47040),
(47060, 47041),
(47079, 47042),
(47064, 47043),
(47082, 47044),
(47099, 47045),
(47067, 47046),
(47068, 47047),
(47094, 47048),
(47129, 47068),
(47420, 47153),
(47429, 47158),
(61020, 61014),
(61029, 61023),
(61076, 61070),
(78171, 78048),
(78134, 78057),
(78269, 78100),
(78270, 78101),
(78367, 78115),
(78411, 78144),
(78010, 78180),
(84133, 84115),
(84149, 84122),
(84150, 84123),
(84245, 84201),
(10054, 10014),
(10076, 10029),
(10093, 10038),
(10097, 10041),
(10170, 10115),
(10178, 10123),
(10188, 10133),
(10194, 10155),
(8028, 8027),
(8029, 8028),
(9099, 9055),
(9157, 9114),
(9170, 9127),
(9171, 9128),
(189700, 9150),
(92236, 92098),
(92300, 92104),
(92301, 92105),
(54183, 54065),
(54202, 54083),
(54203, 54084),
(54300, 54182),
(54301, 54183),
(127198, 127057),
(66033, 66040),
(66033, 66111),
(29007, 29007),
(29008, 29008),
(29010, 29010),
(29078, 29078),
(29079, 29079),
(29080, 29080),
(29081, 29081),
(29084, 29084),
(5082, 5073),
(110168, 110073),
(181387, 181131),
(181387, 181151),
(88112, 88066),
(60025, 60025),
(67008, 67001),
(67010, 67001),
(67014, 67006),
(67052, 67059),
(67053, 67060),
(189714, 20176),
(189719, 20199),
(97040, 97029),
(85163, 85091),
(85272, 85123),
(85316, 85131),
(85317, 85132),
(85318, 85133),
(85319, 85134),
(85341, 85154),
(85342, 85155),
(51125, 51094),
(57204, 57084),
(59085, 59047),
(59153, 59086),
(33214, 33094),
(33215, 33095),
(33128, 33147),
(33146, 33147),
(33157, 33147),
(33176, 33147),
(123028, 123022),
(123081, 123099),
(123174, 123111),
(123177, 123112),
(123028, 123114),
(25165, 25053),
(25245, 25087),
(25270, 25094),
(25271, 25095),
(25272, 25096),
(25314, 25135),
(25318, 25160),
(40016, 40004),
(40017, 40005),
(40018, 40006),
(40033, 40019),
(40034, 40020),
(40085, 40070),
(40086, 40071),
(40087, 40072),
(40088, 40073),
(40089, 40074),
(40091, 40076),
(40092, 40077),
(40093, 40078),
(41013, 41005),
(41103, 41088),
(42029, 42016),
(42030, 42017),
(42031, 42018),
(42034, 42021),
(34068, 34034),
(34072, 34038),
(34098, 34049),
(34126, 34064),
(37009, 37082),
(49031, 49021),
(49034, 49024),
(49044, 49034),
(49085, 49075),
(49093, 49083),
(49094, 49084),
(49095, 49085),
(49096, 49086),
(49097, 49087),
(49100, 49090),
(49101, 49091),
(49105, 49103),
(49105, 49115),
(49106, 49125),
(69135, 69086),
(69013, 69140),
(93112, 93058),
(93245, 93093),
(93298, 93104),
(93299, 93105),
(93368, 93153),
(93372, 93157),
(189472, 93186),
(75011, 75005),
(75123, 75112),
(75127, 75116),
(75130, 75139),
(45099, 45052),
(1025, 1025),
(1150, 1133),
(1152, 1135),
(1161, 1144),
(2092, 2049),
(2143, 2099),
(4116, 4070),
(4117, 4071),
(4168, 4145),
(3018, 3012),
(3057, 3042),
(50105, 50059),
(50125, 50069),
(50211, 50121),
(19019, 19019),
(19030, 19030),
(19134, 19114),
(125009, 125004),
(125011, 125006),
(125023, 125006),
(125047, 125006),
(125012, 125007),
(125011, 125014),
(125023, 125015),
(125047, 125015),
(125032, 125016),
(125182, 125016),
(125183, 125016),
(125189, 125016),
(125194, 125016),
(125195, 125016),
(125032, 125017),
(125184, 125017),
(125194, 125017),
(125195, 125017),
(125032, 125018),
(125195, 125018),
(125196, 125018),
(125182, 125019),
(125183, 125019),
(125196, 125019),
(125040, 125020),
(125182, 125020),
(125184, 125020),
(125176, 125021),
(125066, 125030),
(125189, 125041),
(125194, 125041),
(125189, 125042),
(125195, 125042),
(125176, 125043),
(125196, 125043),
(14147, 14063),
(35133, 35067),
(56109, 56049),
(56128, 56062),
(56235, 56094),
(56301, 56129),
(189279, 56156),
(100172, 100090),
(100305, 100125),
(100112, 100128),
(100431, 100166),
(83084, 83048),
(83118, 83056),
(83177, 83098),
(83242, 83121),
(115176, 115173),
(96073, 96040),
(96075, 96041),
(96076, 96042),
(96126, 96043),
(96081, 96044),
(96096, 96045),
(96165, 96046),
(38143, 38047),
(38211, 38059),
(38245, 38077),
(38247, 38078),
(38248, 38079),
(38362, 38084),
(38363, 38085),
(38364, 38087),
(38365, 38088),
(38366, 38089),
(38367, 38090),
(38368, 38094),
(38369, 38097),
(38370, 38098),
(38371, 38100),
(38372, 38101),
(38373, 38102),
(38374, 38104),
(38375, 38106),
(38376, 38108),
(38377, 38109),
(38378, 38110),
(38379, 38112),
(38380, 38113),
(38381, 38114),
(38382, 38116),
(38383, 38119),
(38384, 38120),
(38385, 38121),
(38386, 38122),
(38387, 38124),
(38388, 38125),
(38389, 38130),
(95263, 95147),
(189476, 95148),
(189477, 95152),
(189478, 95152),
(189479, 95163),
(189480, 95163),
(189481, 95163),
(189482, 95181),
(189483, 95181),
(108003, 108002),
(108008, 108003),
(108027, 108007),
(79372, 79115),
(120168, 120104);
INSERT IGNORE INTO spawnentry_post_velious SELECT e.* FROM spawnentry e JOIN era_019 x ON x.spawngroupID = e.spawngroupID AND x.npcID = e.npcID;
DELETE e FROM spawnentry e JOIN era_019 x ON x.spawngroupID = e.spawngroupID AND x.npcID = e.npcID;
DROP TEMPORARY TABLE era_019;
